# Generated by Django 2.2 on 2019-04-12 20:44

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timecalculator', '0002_auto_20190412_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='items',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, null=True, related_name='packages', to='timecalculator.Product'),
        ),
        migrations.AlterField(
            model_name='package',
            name='places',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, null=True, related_name='packages', to='timecalculator.Place'),
        ),
        migrations.AlterField(
            model_name='package',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='auction_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
