# Generated by Django 2.2 on 2019-04-12 20:45

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timecalculator', '0003_auto_20190412_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='items',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='packages', to='timecalculator.Product'),
        ),
        migrations.AlterField(
            model_name='package',
            name='places',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='packages', to='timecalculator.Place'),
        ),
    ]
